apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy all app microservices
resources:
- complete-demo.yaml
- ingress.yaml
- ./manifests-monitoring/00-monitoring-ns.yaml
- ./manifests-monitoring/01-prometheus-sa.yaml
- ./manifests-monitoring/02-prometheus-cr.yaml
- ./manifests-monitoring/03-prometheus-crb.yaml
- ./manifests-monitoring/04-prometheus-configmap.yaml
- ./manifests-monitoring/05-prometheus-alertrules.yaml
- ./manifests-monitoring/06-prometheus-dep.yaml
- ./manifests-monitoring/07-prometheus-svc.yaml
- ./manifests-monitoring/08-prometheus-exporter-disk-usage-ds.yaml

# Apply Grafana manifests
- ./manifests-monitoring/20-grafana-configmap.yaml
- ./manifests-monitoring/21-grafana-dep.yaml
- ./manifests-monitoring/22-grafana-svc.yaml
# import grafana dashboard
- ./manifests-monitoring/23-grafana-import-dash-batch.yaml

